=== Rizhi-KotE/winapi-handbook/src/test/resources/datasets/test.dtd
<!ELEMENT dataset (
    REQUIREMET*,
    WINAPI_FUNCTION*,
    WINAPI_PARAMETER*,
    WINAPI_USER_ELEMENT*)>

<!ELEMENT REQUIREMET EMPTY>
<!ATTLIST REQUIREMET
    id CDATA #REQUIRED
    category CDATA #REQUIRED
    category_value CDATA #REQUIRED
    function_id CDATA #REQUIRED
>

<!ELEMENT WINAPI_FUNCTION EMPTY>
<!ATTLIST WINAPI_FUNCTION
    ID CDATA #REQUIRED
    NAME CDATA #REQUIRED
    DESCRIPTION CDATA #REQUIRED
    CLASS_ID CDATA #IMPLIED
    syntax CDATA #REQUIRED
    return_type CDATA #REQUIRED
    return_type_description CDATA #REQUIRED
>

<!ELEMENT WINAPI_PARAMETER EMPTY>
<!ATTLIST WINAPI_PARAMETER
    ID CDATA #REQUIRED
    FUNCTION_ID CDATA #IMPLIED
    first_definition CDATA #REQUIRED
    type_definition CDATA #REQUIRED
    description CDATA #REQUIRED
>

<!ELEMENT WINAPI_USER_ELEMENT EMPTY>
<!ATTLIST WINAPI_USER_ELEMENT
    ID CDATA #REQUIRED
    NAME CDATA #REQUIRED
    DESCRIPTION CDATA #REQUIRED
>

=== Rizhi-KotE/winapi-handbook/src/test/resources/datasets/elementWithFunctionsAndParameters.xml
<!--<!DOCTYPE dataset SYSTEM "test.dtd">-->
<dataset>
    <WINAPI_USER_ELEMENT ID="1" NAME="elem" DESCRIPTION="dec"/>
    <WINAPI_FUNCTION ID="1" NAME="func" DESCRIPTION="dec" CLASS_ID="1" return_type="return_type"
                     return_type_description="return_dec" syntax="syntax"/>
    <WINAPI_FUNCTION ID="2" NAME="func" DESCRIPTION="dec" CLASS_ID="1" return_type="return_type"
                     return_type_description="return_dec" syntax="syntax"/>
    <WINAPI_PARAMETER ID="1" description="dec" first_definition="first_def"
                      type_definition="type_def" FUNCTION_ID="1"/>
    <WINAPI_PARAMETER ID="2" description="dec" first_definition="first_def"
                      type_definition="type_def" FUNCTION_ID="1"/>
    <WINAPI_PARAMETER ID="3" description="dec" first_definition="first_def"
                      type_definition="type_def" FUNCTION_ID="2"/>
    <WINAPI_PARAMETER ID="4" description="dec" first_definition="first_def"
                      type_definition="type_def" FUNCTION_ID="2"/>
    <REQUIREMET function_id="1" id="1" category="key" category_value="value"/>
</dataset>
